version: '3'

services:
  sqlite-node:
    image: sqlite-node:0.1
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:38000:8000"
    volumes:
      - ./database:/app/db
    container_name: sqlite-node
    command: ["--host","0.0.0.0","--port","8000"]

  sqlite-browser:
    image: linuxserver/sqlitebrowser
    ports:
      - "0.0.0.0:33000:3000"
      - "0.0.0.0:33001:3001"
    depends_on:
      - sqlite-node
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - ENABLE_UWSGI=true
    volumes:
      - ./database:/config/db
    container_name: sqlite-browser
  #  command: ["sqlitebrowser","/config/db/db.sqlite","--table","csv_data"]

